dist: xenial   # required for Python >= 3.7

language: python
python:
    - "3.7"

install:
    - pip install -r requirements.txt

env:
    - DJANGO_SETTINGS_MODULE=PsyGuideSite.settings

before_script:
    - cd ./PsyGuideSite/
    - python manage.py makemigrations
    - python manage.py migrate
    - coverage run --source=. manage.py test questionnaire --noinput --settings=PsyGuideSite.settings
    # Just running questionnaire tests right now - they all pass.

script: python manage.py test

after_success:
    - coveralls
