site_name: PsyGuide Docs
repo_url: https://github.com/friday-the-13th/Front-end
theme: readthedocs

nav:
- Home: 'index.md'
- User:
    - Home: 'user/home.md'
    - Patient: 'user/patient.md'
    - Flowchart: 'user/flowchart.md'
    - Questionnaire: 'user/questionnaire.md'
- Developer:
    - Layout: 'developer/layout.md'
    - Getting Started: 'developer/getting_started.md'
    - Questionnaires: 'developer/questionnaire.md'
