# Generated by Django 2.1.5 on 2019-02-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name="Patient's First Name")),
                ('first_last', models.CharField(max_length=30, verbose_name="Patient's First Last")),
                ('birthday', models.DateField(blank=True, null=True)),
                ('diagnosis', models.CharField(choices=[('none', 'none'), ('Dp', 'Depression'), ('BDCD', 'Bipolar Disorder Currently Depressed'), ('BDHMD', 'Bipolar Disorder Currently Hypomanic/Manic'), ('MD', 'Mood Disorder'), ('other', 'other')], default='none', max_length=90)),
                ('current_script', models.CharField(max_length=30, verbose_name='Curretn Prescription')),
                ('current_dose', models.CharField(max_length=30, verbose_name='Curretn Dose')),
            ],
        ),
    ]
