# Generated by Django 2.1.5 on 2019-03-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_last',
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_dose',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_script',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
